spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://localhost:3306/uber_wallet
    username: root
    password: Kiran@210800
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8090