spring:
  application:
    name: ride-service

  datasource:
    url: jdbc:mysql://localhost:3306/uber_ride_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Kiran@210800
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

application:
  driver-service:
    url: http://localhost:8083
  user-service:
    url: http://localhost:8082
